services:
    simpleweb.saas.form.type.registration:
        class: %simpleweb.saas.form.type.registration.class%
        arguments:
            - "%fos_user.model.user.class%"
            - "%simpleweb.saas.plan.class%"
        tags:
            - { name: form.type, alias: simpleweb_saas_user_registration }

    simpleweb.saas.registration_listener:
        class: Simpleweb\SaaSBundle\EventListener\RegistrationListener
        arguments:
            - @event_dispatcher
            - @simpleweb.saas.subscription.manager
        tags:
            - { name: kernel.event_subscriber }

    simpleweb.saas.subscription.manager:
        class: %simpleweb.saas.subscription.manager.class%
        arguments:
            - "%simpleweb.saas.subscription.class%"

parameters:
    simpleweb.saas.form.type.registration.class: Simpleweb\SaaSBundle\Form\Type\RegistrationFormType
    simpleweb.saas.subscription.manager.class: Simpleweb\SaaSBundle\Manager\SubscriptionManager
